name: Create Issue on Main Branch Commit
on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Issue
      run: |
        # Define your issue title and body here
        issue_title="Automatic Issue on Commit"
        issue_body="A commit has been pushed to the main branch."

        # Create the issue using the GitHub API
        response=$(curl -X POST -s -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\"}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues")

        # Check if the issue was created successfully
        if [[ $(echo "$response" | jq -r .html_url) != "null" ]]; then
          echo "Issue created successfully: $(echo "$response" | jq -r .html_url)"
        else
          echo "Failed to create issue. Response: $response"
          exit 1
        fi
